#ifndef VOXBLOX_ROS_COMPAT_VISUALIZATION_MSGS_MARKER_H_
#define VOXBLOX_ROS_COMPAT_VISUALIZATION_MSGS_MARKER_H_

#include <visualization_msgs/msg/marker.hpp>

#endif  // VOXBLOX_ROS_COMPAT_VISUALIZATION_MSGS_MARKER_H_
